version: '3'

services:
  migrate:
    image: postgres:latest
    command: >
      bash -c "sleep 10 && psql -h db -U postgres -d db -f /dump.sql"
    volumes:
      - ./dump.sql:/dump.sql
    environment:
      - PGPASSWORD=postgres
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default

  interviewfy_back:
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/backend
    depends_on:
      - db
    networks:
      - default

  interviewfy_front:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - interviewfy_back
    networks:
      - default

networks:
  default:
