version: '3'

services:
  migrate:
    image: postgres:latest
    command: >
      bash -c "sleep 10 && psql -h db -U $POSTGRES_USER -d $POSTGRES_DB -f /dump.sql"
    volumes:
      - ./dump.sql:/dump.sql
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - 5432
